# Generated by Django 4.2.7 on 2026-01-16 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('meaning', models.TextField()),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('system', 'System'), ('manual', 'Manual'), ('context', 'Context'), ('csv', 'CSV')], default='manual', max_length=10)),
                ('is_system', models.BooleanField(default=False)),
                ('created_by_role', models.CharField(choices=[('admin', 'Admin'), ('learner', 'Learner')], default='learner', max_length=10)),
                ('learning_status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('mastered', 'Mastered')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'vocabularies',
                'db_table': 'vocabularies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabulary')),
            ],
            options={
                'db_table': 'vocabulary_topics',
                'unique_together': {('vocabulary', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='topics',
            field=models.ManyToManyField(related_name='vocabularies', through='vocabulary.VocabularyTopic', to='topics.topic'),
        ),
    ]
