# Generated by Django 5.2.10 on 2026-01-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficiency')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='meaning_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Vietnamese Meaning'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='phonetics',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='word_type',
            field=models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('pronoun', 'Pronoun'), ('interjection', 'Interjection'), ('phrase', 'Phrase'), ('idiom', 'Idiom'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
