# Generated by Django 6.0.1 on 2026-01-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_rename_notification_learningnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='words_per_session',
            field=models.PositiveIntegerField(default=10, help_text='Words targeted per study session'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='planned_words',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('missed', 'Missed')], default='upcoming', max_length=15),
        ),
    ]
